server:
  port: 8011
sms:
  aliyun:
    pass-word: 12345
    user-name: 自定义的玩意
    sign: 阿里云
    url: http://aliyun.com/send
  tencent:
    pass-word: 6666
    user-name: 自定义的玩意
    sign: 腾讯云
    url: http://tencent.com/send
